server:
  port: 8081
  servlet:
    context-path: /service

spring:
  application:
    name: ServiceManager-service

  cloud:
    config:
      enabled: false
      discovery:
        enabled: false
    compatibility-verifier:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-boot-client
            client-secret: n93fJNFySDXV4DDazbumydiAoede6fZN
            authorization-grant-type: authorization_code
            scope: openid,roles,profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/realms/mss-authent
            user-name-attribute: preferred_username
            token-uri: http://localhost:8088/realms/mss-authent/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/mss-authent
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:mssservice}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:firas}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web.cors: TRACE
    org.example.aspects: DEBUG
    org.example.interceptors: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

user-service:
  base-url: http://localhost:8081/api/users

service-manager-service:
  base-url: http://localhost:8082/api/services
admin-service:
  base-url: http://localhost:8884/admin


keycloak:
  realm: mss-authent
  auth-server-url: http://localhost:8088/auth
  ssl-required: none
  resource: spring-boot-client
  credentials:
    secret: 8ycLZaqgKIzkHewKwv5OJFdv4v7TR2St
  use-resource-role-mappings: true
