package com.mss.demo.entity.dto;

import lombok.Data;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

@Data
public class ServiceDTO {
    private UUID id;
    private String name;
    private String description;
    private String version;
    private String endpoint;
    private boolean status;
    private String configuration;
    private String pricing;
    private Collection<GroupDTO> groups;
    private OffsetDateTime createdDate;
    private OffsetDateTime lastModifiedDate;
    private String accessToken;

    // Getters and setters are automatically generated by the @Data annotation
}
